//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameServer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: 0,
        ///    &quot;Name&quot;: &quot;Lyra&quot;,
        ///    &quot;Health&quot;: 150.0,
        ///    &quot;Mana&quot;: 100.0,
        ///    &quot;Armor&quot;: 0.0,
        ///    &quot;Resistance&quot;: 15.0,
        ///    &quot;Speed&quot;: 100.0,
        ///    &quot;CriticalChance&quot;: 0.25,
        ///    &quot;CriticalMultiplier&quot;: 1.1,
        ///    &quot;Abilities&quot;: [
        ///      {
        ///        &quot;Name&quot;: &quot;Phantom Strike&quot;,
        ///        &quot;Damage&quot;: {
        ///          &quot;Type&quot;: 0,
        ///          &quot;Amount&quot;: 10.0
        ///        }
        ///      },
        ///      null,
        ///      null,
        ///      null
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: 0,
        ///    &quot;Name&quot;: &quot;Toxin&quot;,
        ///    &quot;Health&quot;: 110.0,
        ///    &quot;Mana&quot;: 100.0,
        ///    &quot;Armor&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
    }
}
